title = "Carme.ai"
baseURL = "https://carme.ai/"
languageCode = "en-us"
theme = "airspace-hugo"
publishDir = "docs"

[menu]

  [[menu.header]]
    weight = 2
    name = "Docs"
    url = "http://docs.carme.ai"
  [[menu.header]]
    weight = 3
    name = "Tutorials"
    url = "/blog"
#  [[menu.header]]
#    weight = 4
#    name = "Training"
#    url = "/service"
  [[menu.header]]
    weight = 4
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Tutorials"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "Terms"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "The Framework for Data Artisans"
    subtitle = "Jupyter and Docker centric data science workflows. <br/>"

  [params.wrapper]
    enable = true
    title = "About Carme"
    italic = "The CarmeLabs teams is a set of academics & data hackers from RPI. "
    paragraph = "Find more about the CarmeLabs team."

  [params.blog]
    enable = true
    title = "Tutorials: How to use the Carme package"
    subtitle = "Learn how to launch a launch Jupyter using a container,  "

  [params.feature]
    enable = true
    title = "We believe in great ideas"
    content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = true
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Contact us. "
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "110 Eight Street, Troy, NY"
      email = "Email: info@carme.ai"

    [params.contact.gmaps]
      title = "Visit us at RPI"
