title = "Carme.ai"
baseURL = "https://carme.ai/"
languageCode = "en-us"
theme = "airspace-hugo"
publishDir = "docs"
googleAnalytics = "UA-32817743-4"

[menu]

  [[menu.header]]
    weight = 2
    name = "Docs"
    url = "https://docs.carme.ai"
  [[menu.header]]
    weight = 3
    name = "Tutorials"
    url = "/blog"
  [[menu.header]]
    weight = 4
    name = "Star on Github"
    url = "https://github.com/CarmeLabs/carme"
  [[menu.header]]
    weight = 5
    name = "Get the Paper"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Tutorials"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "Terms"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "The Framework for Data Artisans"
    subtitle = "Jupyter and Container centric data science workflows for building AI applications. <br/>"

  [params.wrapper]
    enable = true
    title = "About Carme"
    italic = "Why does AI need a framework?"
    paragraph = "Frameworks have long been the friend of the web developers, increasing productivity by easing processes of getting started, building, and deploying applications. Loosely modeled after Laravel, Carme is designed to help data scientists to create and deploy data applications."

  [params.blog]
    enable = true
    title = "Tutorials: How to use Carme"
    subtitle = ""

  [params.feature]
    enable = true
    title = "Like using Jupyter?"
    content = "Carme helps you to use Jupter. Just like you use the jupyter notebook and jupyter lab commands to launch jupyter on your pc, use carme jupyter and carme lab to launch Jupyter in a container. Containerizing jupyter makes it easier to share and scale your analyses. "
    [params.feature.button]
      caption = "View Documentation"
      url = "http://docs.carme.ai"

  [params.call]
    enable = true
    title = "Containers increase reproducablity and scalablity, and Carme helps data scientists to use containers."
    paragraph = "Working with containers allows your infrastructure to become code [this is often referred to as  or infrastructure as code (IAC)]. This ensures that others will be able to reproduce your work, and the Carme package system makes sharing your work a snap.  Containers are also useful when you want to scale an analysis, perhaps moving from your local machine to a GPU in the cloud or from a single GPU server to a Kubernetes cluster for a classroom Jupyterhub instance.  "

  [params.contact]
    enable = true
    title = "Contact us. "
    subtitle = "Stay in touch for latest developments."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "110 Eight Street, Troy, NY"
      email = "Email: info@carme.ai"
    [params.contact.gmaps]
      title = "Visit us in Troy, NY"
